### PR TITLE
Remove private method from interface Message

### PR DESCRIPTION
**Pull request by corny**
This allows to implement own messages beside this package.

### CODE REVIEW

**Comment by jsimonetti** [comment]
Hi @corny,

I am not against removing this, if there is a legitimate reason for doing so. However, at the moment it is entirely possible for you to use the `netlink` package directly in your software should you wish to create custom structures. 

I am keen to understand why you would want to implement your own messages. This private method is in place specifically to ensure that the messages send to and received from the linux kernel are of a format that is compatible with the rtnetlink interface.

**Comment by mdlayher** [comment]
I also don't understand the benefit this would bring.

**Comment by corny** [comment]
I am not able to pass my own Message to `conn.Execute()` like you can see here:
https://github.com/jsimonetti/rtnetlink/compare/master...digineo:addrgenmode

Simply copying the `Execute()` method also doesn't work because it calls private methods.

**Comment by mdlayher** [comment]
Assuming that is a valid rtnetlink message type that is not already supported by the library, why not submit the code upstream instead? If you need something really unusual then I would also encourage using mdlayher/netlink directly.

**Comment by corny** [comment]
You're right - in this case I should use `mdlayher/netlink` directly. My fork was just an attempt to set the `addrgenmode` of interfaces. I switched to using the proc systemd and writing to `/proc/sys/net/ipv6/conf/<ifname>/addr_gen_mode`.

If I have some time to spare I'll try to get this upstream.

**Pull request closed without merging**
