### PR TITLE
link: Return pointers to messages

### PR DESCRIPTION
**Pull request by corny**
this avoids copying of structs

### CODE REVIEW

**Comment by jsimonetti** [comment]
I have no objections to this.
@mdlayher do you see any red flags?

**Comment by mdlayher** [comment]
Seems fine. Pointer indirections aren't always better though. I would be curious what prompted this change, such as benchmarks or profile evidence.

**Comment by corny** [comment]
Good point. I'll try to profile both implementations.

**Comment by jsimonetti** [comment]
Did you have any results about this you can share?

**Comment by corny** [comment]
I used the benchmark:
```golang
func BenchmarkListLink(b *testing.B) {
	b.ReportAllocs()

	// Dial a connection to the rtnetlink socket
	conn, err := rtnetlink.Dial(nil)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	for i := 0; i < b.N; i++ {
		conn.Link.List()
	}
}
```

The new version requires slightly less bytes per operation:
```
BenchmarkOldVersion        10856      107436 ns/op     15598 B/op      162 allocs/op
BenchmarkNewVersion        10000      107544 ns/op     15566 B/op      162 allocs/op
```

**Comment by jsimonetti** [comment]
So, if I understand these results correctly, the copy method currently used appears to scale better with additional links at the cost of a tiny memory size overhead?
I think the overhead is small enough to warrent the scale benefit and we'll keep the current method in place.

Thank you very much for the benchmark though. It is very nice to actually compare with numeric evidence.

**Comment by corny** [comment]
I did 20 tests runs with 5 seconds duration and the performance seems to be equal. Sometimes the old version is faster, sometimes the new version. Beside the performance - don't you the code is cleaner if we avoid copying structs?

**Comment by mdlayher** [comment]
IMHO it's probably not worth the trouble to make the changes (and break callers) since there is no measurable benefit.

**Comment by jsimonetti** [comment]
I concur with @mdlayher here. There is not enough benefit to warrant an API break this big.
I do appreciate your effort in trying to improve the code. Thank you for your time investment!

**Comment by corny** [comment]
Thanks for your feedback. I understand it's not reason to break the API.

**Pull request closed without merging**
