### PR TITLE
[rtnl] add RouteGet method

### PR DESCRIPTION
**Pull request by pmazzini**
`RouteGet` gets a single route to the given destination address.

### CODE REVIEW

**Comment by jsimonetti** [comment]
Thank you for this contribution. This looks fine by me.
This also looks like a prime candidate to include in the integration tests. Would you be willing to add a test for this? You can check out https://github.com/jsimonetti/rtnetlink/blob/master/rtnl/neigh_live_test.go#L10 as an example. This would be very beneficial for this package.
Thank you in advance!

**Comment by pmazzini** [comment]
> This looks fine by me, with the exception of the `rtnl.Route` type. If possible I would like to prevent adding types to this library. Though in this case I am not sure if we can do otherwise.

I added it for consistency, in `neigh.go` there is a `Neigh` type defined. Also to avoid exposing the lower level definitions. I am happy to change it, any suggestions?


> Would you be willing to add a test for this?

Yes, I'll add one.

**Comment by jsimonetti** [comment]
> I added it for consistency, in `neigh.go` there is a `Neigh` type defined. Also to avoid exposing the lower level definitions. I am happy to change it, any suggestions?
Not really to be honest. You are correct that there is also a `rtnl.Neigh`. I am looking at the `rtnl.Route*` API in general and it is a bit diverging. I was hoping to keep it uniform and simple (which is the exact reason for this helper package). Maybe this is the time to add a `rtnl.Route` type. We would definitely have to revisit the rest of the `rtnl.Route*` API to see if we want to change that too, but that can come at a later stage.
@rsmitty and @mdlayher Could you maybe weigh in, since you are big users of the API?

> > Would you be willing to add a test for this?
> 
> Yes, I'll add one.
Awesome. Not having route integration tests here has been a thorn in my eyes for a long time :)

**Comment by jsimonetti** [comment]
Thank you for the update. Looks good imho.
I'll wait for the others to chime in with any ideas before I merge this.

**Comment by jsimonetti** [comment]
I'll merge this for now. We can always revisit this later if need be.
Thank you!

**Pull request merged**
