### PR TITLE
route: Implement support for RTA_EXPIRES

### PR DESCRIPTION
**Pull request by Natolumin**
The RTA_EXPIRES attribute allows creating self-deleting routes after a timer; it is useful for example when installing routes obtained from a DHCP lease.

Sending the attribute with a zero value means the route will be immediately deleted, a very different behaviour from when the attribute is omitted (where the rule does never expire). Because of this we can't just put and retrieve a simple u32 from the attribute

This is one solution I've come up with (which I prefer), there is another approach at https://github.com/Natolumin/rtnetlink/commit/93d6eaaf761921fac7d10f0ba6df64c51544c9aa where we use `time.Duration` instead of uint32, but there are ranges of values that we can't map directly (everything >2^32s) and it advertises higher precision than is actually available since we can set `time.Duration` values to the nanosecond but the kernel API only takes seconds.

In this solution, we declare Expires as a `uint32`, then treat it as `timeout + 1`, so that:
 * The zero value means a timeout of -1 ie `0xffffffff`, the same as not expiring, so we can ignore the zero value when reading or writing. This makes the default behaviour when not specifying a value the same as all the other attributes (where we can omit the attribute on the zero value)
 * A value of `0xffffffff` means the route expires in `0xfffffffe` seconds. This might surprise those who read the kernel documentation expecting 0xffffffff to mean the route does not expire
 * A value of 1 means the route expires immediately (might be surprising)
 * All other values are offset by 1 second. Considering the granularity of timeouts is 1s anyway they were never meant to be very precise so this might be fine ?

Another solution would be to keep the uint32 but only treat 0 as special value and not shift everything else by 1. That makes the timeouts more consistent with what the user specifies, but it means it is impossible to create a route which expires immediately, and if the kernel sends a timeout of 0 we need to special-case it as well (how ?)

### CODE REVIEW

**Comment by jsimonetti** [comment]
Thank you for this PR! I will have to do some thinking wether I like the offset by 1 idea.

**Comment by Natolumin** [comment]
I've gone back and forth several times yesterday on what the best solution is, and in the end I really couldn't find a good reason to create immediately-expiring routes (unlike say, addresses, where you can have preferred_lft=0 but valid_lft>0, when a route expires it's just deleted). So the solution to just special-case zero is maybe less surprising for the end-user so better. It looks like this: https://github.com/Natolumin/rtnetlink/commit/bb2d1ec1a6183463f095973c7ca2961164c00e62

I can update the PR to whichever of the solutions you prefer

**Comment by jsimonetti** [comment]
Ok, so looking through the kernel source, if the attribute is omitted, the route is never deleted, if the attribute is zero is is immediately deleted and any other value will be the timeout in seconds.

I think there is no other way to this then defining `RouteAttributes.Expires` as a `*uint32` and threat nil and omitted and any other value as what the user wants to happen.
This is not an uncommon pattern in this library and has been used in other places where the default struct value does not fit the actual kernel default behaviour.

**Comment by jsimonetti** [comment]
Additionally, zero is a valid value for Expires when retrieving routes from the kernel.
If I query the route table for active routes and a route has expired, but has not yet been deleted, zero would be an appropriate value to receive back from the kernel.

I have not looked at how often the kernel GC's these expired routes, but I can't believe that expired routes will be deleted with microsecond accuracy, so this would not be an unlikely scenario.

**Comment by Natolumin** [comment]
I think there is one thing annoying with the `*uint32` idea, that struct literals become harder to write: 
```go
RouteAttributes{
	OutIface: 2,
	Expires: 255, // This is invalid
}
// You need to allocate a variable and take an indirection
timeout := uint32(255)
RouteAttributes{
	Expires: &timeout,
}
```
Other than that, at least it lets us describe all possible values so at least for correctness it is a better solution

I've updated with *uint32 (and added a basic test) let me know if this is better!

**Comment by jsimonetti** [comment]
Thank you for your contribution!

**Comment by jsimonetti** [comment]
I agree, struct literals are a pain when pointers are involved, but on the other hand in most cases you would probably have a variable/constant holding a (default) timeout value already.

**Pull request merged**
